# Generated by Django 5.2.4 on 2025-07-27 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parametros', models.CharField(max_length=255)),
                ('Resultado', models.CharField(max_length=255)),
                ('DtInclusao', models.DateTimeField(auto_now_add=True)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'db_table': 'Operacao',
                'ordering': ['-DtInclusao'],
            },
        ),
    ]
